spring:
  datasource:
    url: jdbc:mysql://krito3.com:3306/base-scaffold?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: mengxiang3.

  redis:
    port: 6379
    password: mengxiang3.
    database: 0
    host: krito3.com
    timeout: 10000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 100
    key:
      admin: 'ums:admin'
      resourceList: 'ums:resourceList'
    expire:
      common: 86400 # 24小时

rocketmq:
  #nameservice服务器地址（多个以英文逗号隔开）
  name-server: krito3.com:9876
  #生产者配置
  producer:
    #组名
    group: group-base

minio:
  endpoint: http://krito3.com:9000/
  bucketName: pawnshop8
  publicBucketName: pawnshop8
  accessKey: pawnshop8
  secretKey: pawnshop8
  path: /home/videt

taskExecutor:
  coreSize: 10
  maxSize: 50
  queueCapacity: 1000
  keepAliveSeconds: 60
  threadNamePrefix: krito3-